import handleRoute from '../../utils/handleRoute';
import './terms-and-conditions.css';
import Title from '../../components/title/Title';

export default function TermsAndConditions() {
    return (
        <div className="terms-conditions-container">
            <Title type={'component'} />

            <div className="terms-and-conditions-text">
                <p> Lorem, ipsum dolor sit amet consectetur adipisicing elit. Autem numquam modi labore. Non voluptatem ea obcaecati ex illum vitae velit inventore laborum tempore. Exercitationem alias blanditiis odio repudiandae at! Ipsa. Lorem ipsum dolor sit amet consectetur adipisicing elit. Non minima illum, quas iure ullam maxime reiciendis, officia magni perspiciatis mollitia a? Ipsa laborum id voluptatibus alias voluptates molestias? Accusamus, porro? Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia hic fugit necessitatibus vel molestias veniam a sapiente expedita numquam vitae voluptates praesentium odio, voluptatibus atque itaque. Sapiente molestiae corrupti in. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo dolore quidem tempore officia quisquam, autem sit ipsum nam in laboriosam quia itaque quos distinctio eius veritatis adipisci facilis rem maxime! Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aperiam ratione cum adipisci ducimus repudiandae facere voluptatem soluta tempora repellendus. A quisquam atque sequi eius voluptas pariatur repellat quas rerum voluptatum. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eveniet, consequatur! Optio ea praesentium molestias eos? Quam consectetur, esse nesciunt repellendus dolore aspernatur consequatur obcaecati et in molestias, earum consequuntur facilis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel in, nihil, at iusto molestiae totam pariatur aut quidem ipsum porro nisi quod dolorum rerum alias beatae officiis praesentium omnis quam.</p>
                <p> Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eveniet, consequatur! Optio ea praesentium molestias eos? Quam consectetur, esse nesciunt repellendus dolore aspernatur consequatur obcaecati et in molestias, earum consequuntur facilis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo dolore quidem tempore officia quisquam, autem sit ipsum nam in laboriosam quia itaque quos distinctio eius veritatis adipisci facilis rem maxime! Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel in, nihil, at iusto molestiae totam pariatur aut quidem ipsum porro nisi quod dolorum rerum alias beatae officiis praesentium omnis quam. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aperiam ratione cum adipisci ducimus repudiandae facere voluptatem soluta tempora repellendus. A quisquam atque sequi eius voluptas pariatur repellat quas rerum voluptatum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat ipsam itaque nihil beatae laborum, earum consequatur illum ipsum deleniti, quisquam quos! Ullam eius quos, pariatur repellat vero dolore quis atque. Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis perferendis minus nobis praesentium. Fuga mollitia ipsum id fugiat iste dicta esse perspiciatis praesentium, quidem vitae, adipisci cum, eaque ex laudantium.</p>
                <p> Placeat eius vero iusto facilis nostrum inventore, esse consequatur quasi a animi ipsam excepturi nesciunt, quisquam aut, enim alias adipisci ab consequuntur. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eveniet, consequatur! Optio ea praesentium molestias eos? Quam consectetur, esse nesciunt repellendus dolore aspernatur consequatur obcaecati et in molestias, earum consequuntur facilis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel in, nihil, at iusto molestiae totam pariatur aut quidem ipsum porro nisi quod dolorum rerum alias beatae officiis praesentium omnis quam. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo dolore quidem tempore officia quisquam, autem sit ipsum nam in laboriosam quia itaque quos distinctio eius veritatis adipisci facilis rem maxime! Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aperiam ratione cum adipisci ducimus repudiandae facere voluptatem soluta tempora repellendus. A quisquam atque sequi eius voluptas pariatur repellat quas rerum voluptatum.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Placeat eius vero iusto facilis nostrum inventore, esse consequatur quasi a animi ipsam excepturi nesciunt, quisquam aut, enim alias adipisci ab consequuntur. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eveniet, consequatur! Optio ea praesentium molestias eos? Quam consectetur, esse nesciunt repellendus dolore aspernatur consequatur obcaecati et in molestias, earum consequuntur facilis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel in, nihil, at iusto molestiae totam pariatur aut quidem ipsum porro nisi quod dolorum rerum alias beatae officiis praesentium omnis quam. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo dolore quidem tempore officia quisquam, autem sit ipsum nam in laboriosam quia itaque quos distinctio eius veritatis adipisci facilis rem maxime! Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aperiam ratione cum adipisci ducimus repudiandae facere voluptatem soluta tempora repellendus. A quisquam atque sequi eius voluptas pariatur repellat quas rerum voluptatum.</p>
                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Autem numquam modi labore. Non voluptatem ea obcaecati ex illum vitae velit inventore laborum tempore. Exercitationem alias blanditiis odio repudiandae at! Ipsa. Lorem ipsum dolor sit amet consectetur adipisicing elit. Non minima illum, quas iure ullam maxime reiciendis, officia magni perspiciatis mollitia a? Ipsa laborum id voluptatibus alias voluptates molestias? Accusamus, porro? Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia hic fugit necessitatibus vel molestias veniam a sapiente expedita numquam vitae voluptates praesentium odio, voluptatibus atque itaque. Sapiente molestiae corrupti in. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo dolore quidem tempore officia quisquam, autem sit ipsum nam in laboriosam quia itaque quos distinctio eius veritatis adipisci facilis rem maxime! Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aperiam ratione cum adipisci ducimus repudiandae facere voluptatem soluta tempora repellendus. A quisquam atque sequi eius voluptas pariatur repellat quas rerum voluptatum. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eveniet, consequatur! Optio ea praesentium molestias eos? Quam consectetur, esse nesciunt repellendus dolore aspernatur consequatur obcaecati et in molestias, earum consequuntur facilis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel in, nihil, at iusto molestiae totam pariatur aut quidem ipsum porro nisi quod dolorum rerum alias beatae officiis praesentium omnis quam.</p>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eveniet, consequatur! Optio ea praesentium molestias eos? Quam consectetur, esse nesciunt repellendus dolore aspernatur consequatur obcaecati et in molestias, earum consequuntur facilis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo dolore quidem tempore officia quisquam, autem sit ipsum nam in laboriosam quia itaque quos distinctio eius veritatis adipisci facilis rem maxime! Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel in, nihil, at iusto molestiae totam pariatur aut quidem ipsum porro nisi quod dolorum rerum alias beatae officiis praesentium omnis quam. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aperiam ratione cum adipisci ducimus repudiandae facere voluptatem soluta tempora repellendus. A quisquam atque sequi eius voluptas pariatur repellat quas rerum voluptatum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat ipsam itaque nihil beatae laborum, earum consequatur illum ipsum deleniti, quisquam quos! Ullam eius quos, pariatur repellat vero dolore quis atque. Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis perferendis minus nobis praesentium. Fuga mollitia ipsum id fugiat iste dicta esse perspiciatis praesentium, quidem vitae, adipisci cum, eaque ex laudantium.</p>
            </div>

            <div className="info-container">
                <p>
                    If you already read the terms and conditions.{' '}
                    <button className="info-button" onClick={handleRoute('/register')}>
                        Create account
                    </button>
                </p>
            </div>
        </div>
    );
}
